### ISSUE TITLE
need to test drinks/users pages after populating database

### ISSUE THREAD

**Issue by zaneu** [zaneu/cs373-idb#24]
haven't been able to test drinks.html, drink.html, users.html, or user.html due to lack of data

**Comment by pybae** [comment]
I'll get on it sometime later tonight

**Comment by pybae** [comment]
Looks good so far, are there any plans for the nutrition values (if they exist) and the like to be updated in each drink and individual page?

**Comment by pybae** [comment]
Couple problems in #26 and #27

**Comment by zaneu** [comment]
Yea, I intended to add more stuff when I could verify everything else was working. I'll look into #26 and #27 today.

**Comment by pybae** [comment]
Done
