### ISSUE TITLE
Should anything be added to the drinks listing page?

### ISSUE THREAD

**Issue by zaneu** [zaneu/cs373-idb#33]
Currently it just has a number and the name of the drink (which links to the drink's page). Descriptions/recipes are probably too long.

**Comment by pybae** [comment]
Nutritional information is a hit iffy for drinks, as most drinks don't have the content at all. I think it's fine as is for now. How about a short listing of the ingredients though?

**Comment by zaneu** [comment]
It's probably fine. I think ingredient listing is a good idea, but we need to talk about how to make sure it doesn't look cluttered.

Also, I'm having trouble accessing a drink's ingredients. "ingredients" is not a part of the drink model, so obviously drink.ingredients isn't going to work... not really sure what to do

**Comment by pybae** [comment]
Right, we'd have to query the join table for each drink, which does sound like a lot of work. I'm not even sure if that'd be doable in Jinja itself.

**Comment by zaneu** [comment]
Alright, I successfully added an ingredients list to each drink page

**Comment by pybae** [comment]
I think it might be a better idea to put the recipe before the ingredients.

**Comment by pybae** [comment]
Good work though :+1:

**Comment by zaneu** [comment]
Why do you say that? If you're browsing drinks, I feel like ingredients would be one of the first things you want to see. Not saying you're wrong, maybe I'm just not considering something.

**Comment by pybae** [comment]
It's more of an aesthetic thing, it kinda looks off to see paragraphs of text separated by a listing format. If that makes any sense
