### ISSUE TITLE
What should the layout be for individual drink pages?

### ISSUE THREAD

**Issue by zaneu** [zaneu/cs373-idb#36]
currently it's description, then ingredients, then recipe

**Comment by zaneu** [comment]
@pybae let's continue this conversation here. would having the ingredients at the top look too weird?

**Comment by pybae** [comment]
I plan to redesign the website sometime later, I think it's alright as it is for now. What do you think about having a list view on the side?

**Comment by zaneu** [comment]
I think that could look good if done right.
